name: engg3130
channels:
  - vpython
  - conda-forge
dependencies:
  - python=3
  - jupyterlab==3.0.15
  - xeus-python>=0.12.0
  - numpy
  - matplotlib
  - seaborn
  - networkx=2
  - sphinx
  - tqdm
  - future
  - pip
  - pip:
    - empiricaldist
    - jupyterlab-vpython==3.0.4
  - python-lsp-server
  - jupyterlab-lsp
  - vpython==7.6.1
