name: engg3130
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sphinx
  - jupyter
    #  - networkx=1.*
  - networkx
  - nbstripout
  - seaborn
  - tqdm
  - future
