name: engg3130
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyterlab=3
  - xeus-python
  - numpy
  - matplotlib
  - seaborn
  - networkx=2
  - sphinx
  - tqdm
  - future
  - pip
  - pip:
    - empiricaldist
    - jupyter-lsp==0.9.3
  - python-language-server
  - jupyterlab-lsp
