name: engg3130
channels:
  - vpython
  - conda-forge
dependencies:
  - python=3
  - jupyterlab=3
  - xeus-python>=0.12.0
  - numpy
  - matplotlib
  - seaborn
  - networkx=2
  - sphinx
  - tqdm
  - future
  - pip
  - pip:
    - empiricaldist
    - jupyterlab-vpython
  - python-language-server
  - jupyterlab-lsp
  - vpython
